add plugin integration tests
UnitTestBot/UTBotCpp pull request #104
Opened 2022-03-01 14:37 UTC by antipeon

2022-03-15 14:24 UTC, antipeon commented on docker/action-scripts/build-and-unit-tests.sh
> +#./UTBot_UnitTests --verbosity info --log `pwd`
need restore

2022-03-15 14:24 UTC, antipeon commented on .github/workflows/build-utbot.yml
> +#          run: npm test ./integration-tests/c-example --extensionDevelopmentPath=./vscode-plugin --extensionTestsPath=./vscode-plugin/out/test/suite/index
remove

2022-03-23 14:09 UTC, ladisgin reviewed
Probably we can use separate CMakeLists.txt or some scripts instead of copy-paste c-example files?

2022-03-23 14:09 UTC, ladisgin commented on docker/action-scripts/build-vsix-and-integration-tests.sh
> +#run integration tests
empty scope

2022-03-23 14:09 UTC, ladisgin commented on integration-tests/c-example-mini/.gitignore
> +utbot-tests/
add endline

2022-04-05 14:31 UTC, ladisgin requested changes

2022-04-05 14:31 UTC, ladisgin commented on .github/workflows/build-utbot.yml
> +          chmod +x server/build/utbot
useless

2022-04-05 14:31 UTC, ladisgin commented on docker/action-scripts/integration-tests.sh
> +echo "VSCODE_VERSION_DIR=$VSCODE_VERSION_DIR"
duplicate vscode-plugin/src/test/run.sh

2022-04-05 14:31 UTC, ladisgin commented on vscode-plugin/src/test/suite/projectTests.test.ts
> +        openFile, PARAMETRIZED_TEST_MODE,
one var per line

2022-04-07 12:17 UTC, ladisgin approved these changes

2022-04-07 12:41 UTC, merged