Add interactive mode
UnitTestBot/UTBotCpp pull request #114
Opened 2022-03-11 05:42 UTC by sava-cska

Now interactive mode doesn't work on generation tests for project or folder, but for file all are fine. For file `linked-list.cpp` generation time equals 52s for 1 parallel process, 36s - for 5 and 20s - for 10. For other files it's impossible to see difference because number of functions in files are small

2022-03-11 06:28 UTC, korifey commented
- Please show the difference with and without interactive mode for file with 100 functions
- why it doesn't work for folder?

2022-03-11 12:27 UTC, sava-cska commented
Generation on file `big-linked-list.c` with 100 functions spends 981 seconds without interactive mode, 948 seconds with 1 process, 485 with 5 process and 262 seconds with 10 process

2022-03-11 12:44 UTC, korifey commented
please make a table in markdown with column:
1. Number of functions in file (1, 5, 10, 50, 100, 500, 1000)
2. Execution time without interactive in sec
3. Execution time with interactive in sec

2022-03-16 10:14 UTC, ladisgin requested changes

2022-03-16 10:14 UTC, ladisgin commented on server/test/framework/External_Call_Test.cpp
> +// Created by gWX1077059 on 20.12.2021.
delete this file

2022-03-16 10:14 UTC, ladisgin commented on server/src/Tests.cpp
> +    //We should turn off symbolic stdin, because it doesn't work correct with interactive mode
add TODO

2022-03-16 14:09 UTC, sava-cska commented on server/test/framework/External_Call_Test.cpp
> +// Created by gWX1077059 on 20.12.2021.
Ok

2022-03-16 14:24 UTC, sava-cska commented on server/src/Tests.cpp
> +    //We should turn off symbolic stdin, because it doesn't work correct with interactive mode
Ok

2022-03-25 09:34 UTC, ladisgin requested changes

2022-03-25 09:34 UTC, ladisgin commented on server/src/tasks/BaseForkTask.cpp
> +                if (killChildStatus == -1 || WEXITSTATUS(killChildStatus) > 1) {
also add check WIFEXITED before WEXITSTATUS

2022-03-25 09:37 UTC, sava-cska commented on server/src/tasks/BaseForkTask.cpp
>              grpc_postfork_child();
Ok

2022-03-25 09:42 UTC, sava-cska commented on server/src/tasks/BaseForkTask.cpp
> +                std::string pkillCommand = "pkill " + pkillParent + " " + pkillSignal;
Ok

2022-03-25 09:57 UTC, sava-cska commented on server/src/tasks/BaseForkTask.cpp
> +            if (!redirectOutput() || pgidStatus != 0) {
Ok

2022-03-25 10:05 UTC, sava-cska commented on server/src/tasks/BaseForkTask.cpp
> +                if (killChildStatus == -1 || WEXITSTATUS(killChildStatus) > 1) {
Ok

2022-03-25 12:18 UTC, ladisgin requested changes

2022-03-25 12:18 UTC, ladisgin commented on server/src/Tests.cpp
> +    //TODO: We should turn off symbolic stdin, because it doesn't work correct with interactive mode
Change top "we need modify symbolic stdin for work with interactive mode"

2022-03-25 12:18 UTC, ladisgin commented on server/src/tasks/BaseForkTask.cpp
> +                exit(pgidStatus);
use BaseForTask fail code

2022-03-25 14:13 UTC, sava-cska commented on server/src/tasks/BaseForkTask.cpp
> +                exit(pgidStatus);
Done

2022-03-25 14:46 UTC, ladisgin approved these changes

2022-03-25 15:11 UTC, merged