Fix coverage generation
UnitTestBot/UTBotCpp pull request #142
Opened 2022-04-07 15:53 UTC by antipeon

2022-04-12 09:27 UTC, antipeon commented
in `bin` target was .o file: ![Screenshot (70)](https://user-images.githubusercontent.com/48559516/162927734-d5b092ff-45d3-42b1-bce4-9e7f5a0cb1c2.png)
now test executable: ![Screenshot (68)](https://user-images.githubusercontent.com/48559516/162928126-32f832b4-e19a-46ec-bcd4-bae7676ad744.png)
and coverage is shown: ![Screenshot (69)](https://user-images.githubusercontent.com/48559516/162928212-1d98c92f-60d8-48c2-8c93-01eabdc9a19d.png)

2022-04-12 09:29 UTC, antipeon commented
for .so files remains unchanged: 
![Screenshot (71)](https://user-images.githubusercontent.com/48559516/162928535-147546c3-1cd4-43d1-b9bf-5255f5ad8e41.png)
coverage was already shown:
![Screenshot (72)](https://user-images.githubusercontent.com/48559516/162928580-a5bfa2e5-48be-43d4-81d0-c210fd9c6e01.png)

2022-04-13 08:18 UTC, ladisgin requested changes
squash commits

2022-04-13 08:18 UTC, ladisgin commented on server/src/printers/NativeMakefilePrinter.cpp
> +        {
Use same style as other file. Move open brackets on same line as if statement.

2022-04-18 08:23 UTC, ladisgin approved these changes

2022-04-18 08:49 UTC, merged