fix icon for failed test
UnitTestBot/UTBotCpp pull request #202
Opened 2022-04-26 10:26 UTC by antipeon

2022-04-26 10:28 UTC, antipeon commented
Squash + check tests again for [pr-188](https://github.com/UnitTestBot/UTBotCpp/pull/188)

2022-05-04 08:12 UTC, ladisgin commented
check tests again

2022-05-05 05:24 UTC, ladisgin requested changes

2022-05-05 05:24 UTC, ladisgin commented on server/test/framework/Server_Tests.cpp
> +            {testsgen::TEST_FAILED, 4},
We wait that our tests failed?

2022-05-05 05:24 UTC, ladisgin commented on server/test/framework/Syntax_Tests.cpp
> -        testUtils::checkStatuses(statusMap, tests);
Looks like this test doesn’t check anything

2022-05-05 05:27 UTC, ladisgin commented on server/test/framework/TestUtils.cpp
> -            EXPECT_TRUE((testsgen::TestStatus::TEST_PASSED == status) ||
We don’t need delete check

2022-05-05 10:14 UTC, antipeon commented
Hanging until failed tests are removed

2022-05-17 14:39 UTC, antipeon commented
remove status check for error suite

2022-05-19 15:58 UTC, ladisgin approved these changes

2022-05-19 17:12 UTC, merged