Fix problem with namespace
UnitTestBot/UTBotCpp pull request #230
Opened 2022-05-13 15:11 UTC by sava-cska

2022-05-16 09:07 UTC, ladisgin requested changes

2022-05-17 08:51 UTC, sava-cska commented on server/src/types/TypesResolver.cpp
> +    std::string currentStructName = canonicalType.getNonReferenceType().getUnqualifiedType().getAsString();
Ok

2022-05-17 08:51 UTC, sava-cska commented on server/src/types/TypesResolver.cpp
> +    std::string currentEnumName = canonicalType.getNonReferenceType().getUnqualifiedType().getAsString();
Ok

2022-05-17 08:54 UTC, sava-cska commented on server/src/types/TypesResolver.cpp
> +            fullname[currentStructName] = fullname[parentRecordName] + "::" + currentStructName;
No

2022-05-17 08:54 UTC, sava-cska commented on server/src/types/TypesResolver.cpp
> +    fullname.insert(std::make_pair(currentStructName, currentStructName));
All will be ok

2022-05-17 20:17 UTC, ladisgin approved these changes

2022-05-17 20:18 UTC, merged