Add support symbolic input/output for C
UnitTestBot/UTBotCpp pull request #315
Opened 2022-07-06 07:25 UTC by sava-cska

2022-07-12 07:54 UTC, ladisgin requested changes

2022-07-12 08:35 UTC, sava-cska commented on server/src/printers/KleePrinter.cpp
> +void KleePrinter::writeMain(const Tests &tests,
Rename

2022-07-12 08:35 UTC, sava-cska commented on server/src/printers/KleePrinter.cpp
> +        entryPoint += PrinterUtils::WRAPPED_SUFFIX;
Rename

2022-07-12 09:36 UTC, vol0n approved these changes

2022-07-13 08:36 UTC, ladisgin requested changes

2022-07-13 08:36 UTC, ladisgin commented on server/src/Tests.cpp
> +        sourceFilePath = tests.sourceFilePath;
move from `for`

2022-07-13 08:36 UTC, ladisgin commented on server/src/printers/Printer.h
> +        std::string stringFunctionCall(const std::string &functionName,
strFunctionCall has same functionality

2022-07-13 09:22 UTC, sava-cska commented on server/src/printers/Printer.h
> +        std::string stringFunctionCall(const std::string &functionName,
No

2022-07-15 12:31 UTC, ladisgin approved these changes

2022-07-15 13:07 UTC, merged