#332 Use UTBotCpp as static analyzer and report results in SARIF
UnitTestBot/UTBotCpp pull request #333
Opened 2022-07-19 15:18 UTC by alexey-utkin

- SARIF generation in server and CLI modes
- auto open SARIF result in MS plugin after the run, if MS plugin has been installed
- backup old SARIF reports with creation-date timestamp in name

2022-07-19 15:49 UTC, sava-cska requested changes

2022-07-19 16:17 UTC, alexey-utkin commented on server/test/suites/cli/goldenImage/codeAnalysis/project_code_analysis.sarif
> +}
It is auto-generated. So as-is.

2022-07-20 08:30 UTC, alexey-utkin commented on server/src/streams/tests/ServerTestsWriter.cpp
> +}
fixed

2022-07-20 08:30 UTC, alexey-utkin commented on server/src/printers/TestsPrinter.cpp
> +    auto& testCases = methodDescription.suiteTestCases[targetSuiteName];
fixed

2022-07-20 12:49 UTC, sava-cska requested changes

2022-07-20 13:27 UTC, alexey-utkin commented on server/src/KleeRunner.cpp
> +    std::function<void(tests::Tests &tests)> prepateTests = [&](tests::Tests &tests) {
fixed

2022-07-20 17:07 UTC, ladisgin requested changes

2022-07-21 09:23 UTC, alexey-utkin commented on server/src/KleeRunner.cpp
> +                            std::string content((std::istreambuf_iterator<char>(fileWithError)),
No. Please read https://en.wikipedia.org/wiki/Most_vexing_parse
https://stackoverflow.com/questions/2912520/read-file-contents-into-a-string-in-c

2022-07-21 09:25 UTC, alexey-utkin commented on server/src/printers/TestsPrinter.cpp
> +                    std::vector<Tests::MethodTestCase> &testCases =methodDescription.testCases;
fixed

2022-07-21 09:33 UTC, alexey-utkin commented on server/src/printers/TestsPrinter.cpp
> +                        std::stringstream ss;
fixed

2022-07-21 09:38 UTC, alexey-utkin commented on server/src/SARIFGenerator.cpp
> +                                    if (Paths::isSubPathOf(projectContext.buildDir, fullPathInProject)) {
Seems we would like to skip any non-user code. Let it be as it is.

2022-07-21 11:12 UTC, alexey-utkin commented on server/src/SARIFGenerator.cpp
> +    fs::path getInProjectPath(const fs::path &path, const fs::path &src) {
fixed

2022-07-21 11:16 UTC, ladisgin approved these changes
squash commits

2022-07-21 12:48 UTC, sava-cska approved these changes

2022-07-21 13:11 UTC, merged