Not support anonymous union in struct #317
UnitTestBot/UTBotCpp pull request #391
Opened 2022-08-22 09:55 UTC by alexey-utkin

2022-08-23 06:37 UTC, alexey-utkin reviewed
Fixing
[PERF] UTBot consumes CPU in spinlocks #382

2022-08-23 06:50 UTC, alexey-utkin commented on server/src/Server.cpp
> +            std::this_thread::sleep_for(100ms);
[PERF] UTBot consumes CPU in spinlocks #382

2022-08-23 06:50 UTC, alexey-utkin commented on server/src/Tests.h
> -        static std::shared_ptr<EnumValueView> enumView(const std::vector<char> &byteArray,
Group enum and struct-like. Seems they need to be joined in the future.

2022-08-23 06:50 UTC, alexey-utkin commented on server/src/printers/KleeConstraintsPrinter.cpp
> +        ss << LINE_INDENT() << "// No constraints for " << state.curElement << NL;
Indent can include the inline comment, so rename it to indent.

2022-08-23 06:50 UTC, alexey-utkin commented on server/src/printers/KleeConstraintsPrinter.cpp
> +                                      isStruct ? state.endString : false,
That is still essential difference between struct and union. Need to be investigated (in progress).

2022-08-23 06:50 UTC, alexey-utkin commented on server/src/printers/KleeConstraintsPrinter.cpp
> +                genStubForStructFunctionPointerArray(state.curElement, field,
no more `just by name` access. That leads to unpredictable errors.

2022-08-23 06:50 UTC, alexey-utkin commented on server/src/printers/TestsPrinter.cpp
> +    int longestFieldIndexForUnionInit = view->getLongestFieldIndexForUnionInit();
So now we are printing all the fields in union, but commenting all, except the longest.

2022-08-23 06:50 UTC, alexey-utkin commented on server/src/types/Types.cpp
> -        {
the subject of bugfix.

2022-08-23 06:50 UTC, alexey-utkin commented on server/src/types/Types.cpp
> -              if (isUnion(type)) {
Has no direct influence to the tests

2022-08-23 06:50 UTC, alexey-utkin commented on server/src/types/Types.cpp
> -              if (isStruct(type)) {
Has no direct influence to the tests

2022-08-23 06:50 UTC, alexey-utkin commented on server/src/types/Types.cpp
> +    const EnumEntry &entry = valuesToEntries.at(value);
Has no const `operator[]`, so changed.

2022-08-23 15:06 UTC, ladisgin requested changes

2022-08-23 15:44 UTC, alexey-utkin commented on server/src/Tests.cpp
> +//UnionValueView::UnionValueView(
done

2022-08-23 15:45 UTC, alexey-utkin commented on server/src/types/Types.h
>          bool isStruct(uint64_t id) const;
done

2022-08-24 13:25 UTC, alexey-utkin commented on server/src/types/Types.h
> +        int longestFieldIndexForUnionInit;
done

2022-08-24 13:25 UTC, alexey-utkin commented on server/src/printers/TestsPrinter.cpp
> +        else {
done

2022-08-24 15:52 UTC, ladisgin approved these changes

2022-08-24 15:55 UTC, merged