Reformat build structure
UnitTestBot/UTBotCpp pull request #457
Opened 2022-09-12 14:19 UTC by ladisgin

2022-09-12 16:32 UTC, sava-cska requested changes

2022-09-12 16:32 UTC, sava-cska commented on server/src/Paths.h
> +    static inline fs::path getUTBotFiles(const utbot::ProjectContext &projectContext) {
Return thsi function to cpp file

2022-09-21 14:53 UTC, alexey-utkin approved these changes

2022-09-22 07:53 UTC, sava-cska approved these changes

2022-09-22 08:05 UTC, merged