fix: detect source paths from compile_commands.json by default
UnitTestBot/UTBotCpp pull request #51
Opened 2022-01-20 23:19 UTC by antipeon

2022-01-24 09:55 UTC, antipeon commented
Nothing in srcFolders -> auto generate from compile_commands.json
![Screenshot (4)](https://user-images.githubusercontent.com/48559516/150760714-05344373-29ad-4dbb-b117-a3cc3ba64b58.png)
![Screenshot (6)](https://user-images.githubusercontent.com/48559516/150760749-474e4785-7b03-4780-adea-eca541874908.png)

2022-01-24 10:01 UTC, antipeon commented
something in srcFolders -> use it for generateForProject
![Screenshot (9)](https://user-images.githubusercontent.com/48559516/150761853-a94a1425-41ef-4fca-a616-ef5e4bce85a9.png)
![Screenshot (10)](https://user-images.githubusercontent.com/48559516/150761861-e96c2e8e-0fda-4c2c-abba-c325ead1c5cf.png)

2022-01-27 13:25 UTC, ladisgin requested changes

2022-01-27 13:25 UTC, ladisgin commented on server/src/Server.cpp
> +            testGen.serverBuildDir, testGen.testingMethodsSourcePaths, testGen.compilationDatabase, typesHandler,
rename back

2022-01-27 13:25 UTC, ladisgin commented on server/src/Server.h
> +                TestGenT testGen{ request, testsWriter.get(), testMode};
return space

2022-01-27 13:25 UTC, ladisgin commented on server/src/testgens/ProjectTestGen.cpp
> +        autoDetectSourcePathsIfNotEmpty();
add if else

2022-01-27 13:25 UTC, ladisgin commented on server/src/testgens/ProjectTestGen.h
> +    vector<fs::path> getSourcePathCandidates();
maybe make const

2022-01-27 15:23 UTC, ladisgin commented on server/src/testgens/ProjectTestGen.cpp
> +                               bool isGenerateForProject)
change name back

2022-01-27 15:37 UTC, ladisgin commented on server/src/Paths.cpp
> +    const std::vector<std::string> headerExtensions({".hh", ".hpp", ".hxx"});
rename

2022-01-27 15:37 UTC, ladisgin commented on server/src/Paths.cpp
> +    const std::string CSourceExtension = ".c";
change to vector

2022-01-27 16:24 UTC, ladisgin approved these changes

2022-01-31 12:16 UTC, merged