External variables support (closes #514)
UnitTestBot/UTBotCpp pull request #522
Opened 2022-10-31 10:08 UTC by Lana243

Closes #514 

To fix the problem extern variable declaration was added to KLEE wrapper and gtest file.

2022-11-07 08:21 UTC, alexey-utkin commented
Seems currenly we get a problem with tests
```
[  FAILED  ] 36 tests, listed below:
[  FAILED  ] Regression_Test.Incomplete_Array_Type
[  FAILED  ] Regression_Test.Global_Char_Array
[  FAILED  ] Regression_Test.Global_Array_Of_Pointers
[  FAILED  ] Server_Test.Globals
[  FAILED  ] Syntax_Test.Pointer_Return_Test_1
[  FAILED  ] Syntax_Test.Pointer_Return_Test_2
[  FAILED  ] Syntax_Test.Pointer_Return_Test_3
[  FAILED  ] Syntax_Test.Return_Long_Long_Array
[  FAILED  ] Syntax_Test.Structs_With_Arrays_Parameter_Test_1
[  FAILED  ] Syntax_Test.Structs_With_Arrays_Return_Test_1
[  FAILED  ] Syntax_Test.Struct_With_Double_Pointer
[  FAILED  ] Syntax_Test.Return_Const_Char_Pointer_1
[  FAILED  ] Syntax_Test.Return_Const_Char_Pointer_2
[  FAILED  ] Syntax_Test.Return_Const_Struct_Pointer_1
[  FAILED  ] Syntax_Test.Return_Int_Array
[  FAILED  ] Syntax_Test.Return_Void2D
[  FAILED  ] Syntax_Test.Return_Null_Pointer
[  FAILED  ] Syntax_Test.Return_Null_Struct
[  FAILED  ] Syntax_Test.Multi_Array_1
[  FAILED  ] Syntax_Test.Multi_Pointer_1
[  FAILED  ] Syntax_Test.Struct_With_Multi_Array
[  FAILED  ] Syntax_Test.Multi_Pointer_Struct
[  FAILED  ] Syntax_Test.Return_Struct_With_Array
[  FAILED  ] Syntax_Test.Sum_Matrix
[  FAILED  ] Syntax_Test.Count_Dashes
[  FAILED  ] Syntax_Test.Accept_Const_Int_Pointer_Pointer
[  FAILED  ] Syntax_Test.UnnamedTypeUnionField
[  FAILED  ] Syntax_Test.UnnamedTypeStructField
[  FAILED  ] Syntax_Test.AnonymousUnionField
[  FAILED  ] Syntax_Test.AnonymousStructField
[  FAILED  ] Syntax_Test.Pass_Forward_Decl
[  FAILED  ] Syntax_Test.Duplicate_Struct
[  FAILED  ] Syntax_Test.Global_Unnamed_Variable
[  FAILED  ] Syntax_Test.bitfields_check_simple_signed_str
[  FAILED  ] Syntax_Test.bitfields_check_fields_bounds
[  FAILED  ] Syntax_Test.bitfields_check_unnamed
```

2022-11-24 07:15 UTC, ladisgin requested changes

2022-11-24 07:15 UTC, ladisgin commented on server/src/printers/KleePrinter.cpp
> +    CollectionUtils::apply(tests.externVariables, [this](const Tests::TypeAndVarName &var) {
Same as server/src/printers/TestsPrinter.cpp:66

2022-11-24 07:15 UTC, ladisgin commented on server/src/printers/KleePrinter.cpp
> +    CollectionUtils::apply(tests.externVariables, [this](const Tests::TypeAndVarName &var) {
useless apply

2022-11-28 10:46 UTC, ladisgin approved these changes

2022-11-28 12:22 UTC, sava-cska approved these changes

2022-11-28 12:41 UTC, merged