Add rvalue support
UnitTestBot/UTBotCpp pull request #551
Opened 2022-11-26 08:12 UTC by ladisgin

2022-11-28 09:40 UTC, Lana243 requested changes

2022-11-28 09:40 UTC, Lana243 commented on server/src/printers/TestsPrinter.cpp
> +            args.push_back(param.name);
These lines duplicates code from Printer.cpp:284-290. I'd recommend to move this ifs to simple method in Printer.cpp

2022-11-30 09:03 UTC, Lana243 approved these changes
LGTM

2022-12-01 08:52 UTC, sava-cska approved these changes

2022-12-01 10:21 UTC, merged