Adding support for multiple variables of the same type to a plugin for vscode
UnitTestBot/UTBotCpp pull request #585
Opened 2023-02-15 07:13 UTC by Nypiaka

2023-03-07 13:18 UTC, ladisgin commented on server/test/framework/Server_Tests.cpp
> +        static bool comparator(const std::string firstVar, const std::string secondVar, bool mustEqual, bool isInt){
Bad naming

2023-03-07 13:18 UTC, ladisgin commented on server/test/framework/Server_Tests.cpp
> +        static bool comparator(const std::string firstVar, const std::string secondVar, bool mustEqual, bool isInt){
Bad naming of parameter

2023-03-15 13:17 UTC, ladisgin requested changes

2023-03-15 13:17 UTC, ladisgin commented on server/test/framework/Server_Tests.cpp
> +        void checkDifferentVariablesTrue_C(BaseTestGen &testGen){
unnecessary extract to function

2023-03-15 13:17 UTC, ladisgin commented on server/test/framework/Server_Tests.cpp
> +        void checkDifferentVariablesFalse_C(BaseTestGen &testGen){
unnecessary extract to function

2023-03-15 13:45 UTC, Nypiaka commented on server/test/framework/Server_Tests.cpp
> +        void checkDifferentVariablesTrue_C(BaseTestGen &testGen){
done

2023-03-15 15:14 UTC, ladisgin approved these changes

2023-03-15 15:14 UTC, merged