feat: show numbers of regression and error suites in generated tests
UnitTestBot/UTBotCpp pull request #66
Opened 2022-02-02 15:58 UTC by antipeon

2022-02-03 09:10 UTC, antipeon commented
![Screenshot (23)](https://user-images.githubusercontent.com/48559516/152313084-8980d357-c305-4e54-ad0b-e6621e678cc5.png)

2022-02-08 12:59 UTC, antipeon commented
![first](https://user-images.githubusercontent.com/48559516/152991783-cda37585-6b98-41ea-a876-86f439623814.png)
![second](https://user-images.githubusercontent.com/48559516/152991793-f4b53726-c27e-4c6e-ba9d-f7e7c8f9aae4.png)
![third](https://user-images.githubusercontent.com/48559516/152991800-06202c21-6d00-4568-9d2e-51d62fefc44b.png)

2022-02-15 09:27 UTC, ladisgin requested changes

2022-02-15 09:27 UTC, ladisgin commented on vscode-plugin/src/logger.ts
> +                vscodeOutChannelForMoreThanDebug: {
rename

2022-02-15 09:27 UTC, ladisgin commented on vscode-plugin/src/responses/responseHandler.ts
> +                    const testsNumberInErrorSuite = (codeText.match(/TEST\(error/g) || []).length;
Can count incorrect, if has "/TEST\(error/g)" into test body.

2022-02-15 13:52 UTC, ladisgin requested changes

2022-02-15 13:52 UTC, ladisgin commented on server/src/printers/TestsPrinter.cpp
> +    uint32_t regressionMethodsNumber = printSuiteAndReturnMethodsCount(Tests::DEFAULT_SUITE_NAME, tests.methods);
unused variables

2022-02-17 13:50 UTC, ladisgin approved these changes

2022-02-17 14:03 UTC, merged